# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d683260b40c9956da9848d7902099f7e48d53adb7fe41342c863322dfd299f7e36a7a0beee7da739c608f5df4583cef433d3776b53014a9302585c21ae0701a

test:
  secret_key_base: 4cf7d0661edcbbc9d2c39bc7002b8c449c82293f0069e94dad972f5424e4883a9ecc5f35e14725dd9387d910779fdcebce8d372d9565a188490ecde9a020701a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
